### ISSUE TITLE
aktueller Status: work in progress - deploying

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-openstack#3]
Wie geht es vorwärts?

Was ist der Status?

**Comment by rtt-mmk** [comment]
wird die Tage deployt

**Comment by DO1JLR** [comment]
okay, spannend.

Koordinieren wir das oder machst du das einfach mal blind drauf los?

Beispielsweise das WE gemeinsam vor Ort in der Toolbox?

**Comment by rtt-mmk** [comment]
ganz ehrlich, nach deinem Verhalten, Äußerungen und Handlungen (wie u.a. Stromstecker eines ganzen Raumes ziehen oder Zugang verweigern, wenn man mal was richten will) der letzten Zeit gibt es da für mich mit Dir alleine nichts mehr zu koordinieren. 

Hab dadurch vor ein paar Tagen schlicht beschlossen, ich deploy openstack per Ansible, so dass es das vorhandene Netzwerk nicht stört auf die Server, die ich eingebracht habe sowie verwalte und gut ist. Dann kommen die Ansible-Deply-Scripte für alle einsehbar in diese Repo. Dann kann ich am Tag der offenen Tür in Ruhe meine Vortrag dazu halten. Und mich so im Verein einbringen. 

Im Prinzip wollte ich mehr machen und das Netzwerk verbessern, das war mit Dir die letzten 3 Monate aber leider nicht möglich.

Alles andere ist mir so einfach meine Nerven echt nicht mehr wert. Das ist ein Verein in dem jeder die gleichen Rechte und Pflichten hat und alles Andere brauch ich nicht länger. Erst recht nicht ausgespielt und, dass irgendein Spielchen mit Zugängen, Irgnorieren von einfachsten Fragen, Nachrichten oder Infos, wenn man sich einbringen will. 

damit ist das hier closed.
